stages:
  - test

cache:
  paths:
    - .cache/pip
    - .tox
    - venv

test-3.7:
  stage: test
  image: python:3.7
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate
  script:
    - tox -e py37

test-3.8:
  stage: test
  image: python:3.8
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate
  script:
    - tox -e py38

test-3.9:
  stage: test
  image: python:3.9
  before_script:
    - pip install poetry
    - poetry install
    - source `poetry env info --path`/bin/activate
  script:
    - tox -e py39

docs-job:
  stage: test
  image: python:3.7
  before_script:
    - pip install -r requirements.txt
    - pip install -r docs/requirements.txt
    - apt-get update 
    - apt-get install make
  script:
    - make -C docs/ clean html