stages:
  - test

default:
  image: python:3.7

unittest-job:
  stage: test
  before_script:
    - apt-get update
    - apt-get install poetry
    - poetry install
    - apt-get install -y locales
    - sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen
    - locale-gen
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - export LC_ALL=en_US.UTF-8
  script:
    - poetry run test

docs-job:
  stage: test
  before_script:
    - pip install -r requirements.txt
    - pip install -r docs/requirements.txt
    - apt-get update 
    - apt-get install make
  script:
    - make -C docs/ clean html