stages:
  - test

default:
  image: python:3.7

unittest-job:
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - tox

docs-job:
  stage: test
  before_script:
    - pip install -r requirements.txt
    - pip install -r docs/requirements.txt
    - apt-get update 
    - apt-get install make
  script:
    - make -C docs/ clean html